# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven App

on:
  workflow_dispatch


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -f java-maven-sonar-argocd-helm-k8s/spring-boot-app/pom.xml clean package


  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk test
        run: snyk test 
  
 


  # build-docker-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build Docker image
  #       run:  docker buildx build -t netflix-clone:latest .


  #     - name: Tag Docker image
  #       run: docker tag netflix-clone:latest davidayo97/netflix-latest:${GITHUB_SHA}

  #     - name: Show Docker images
  #       run: docker images

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Push Docker image
  #       run: docker push davidayo97/netflix-latest:${GITHUB_SHA}
  
      

    
