# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven App

on:
  workflow_dispatch


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -f java-maven-sonar-argocd-helm-k8s/spring-boot-app/pom.xml clean package

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 (You can change the version if needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Cache SonarCloud scanner to speed up subsequent builds
      - name: Cache SonarCloud scanner
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}

      # Run the SonarCloud scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-project-key: davidolufemi_Jenkins-Zero-To-Hero
          sonar-organization: davidolufemi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
      

    
